// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package iam_pb is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	MessageCSR
	SignedMessage
*/
package iam_pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// MessageType ...
type MessageType int32

const (
	MessageType_MessageType_Initialize MessageType = 0
	MessageType_MessageType_MessageCSR MessageType = 1
	MessageType_MessageType_MessageCOT MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MessageType_Initialize",
	1: "MessageType_MessageCSR",
	2: "MessageType_MessageCOT",
}
var MessageType_value = map[string]int32{
	"MessageType_Initialize": 0,
	"MessageType_MessageCSR": 1,
	"MessageType_MessageCOT": 2,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

// Request CSR
type MessageCSR struct {
	PeerId           *string `protobuf:"bytes,1,req,name=peer_id" json:"peer_id,omitempty"`
	Cid              *string `protobuf:"bytes,2,req,name=cid" json:"cid,omitempty"`
	Op               *string `protobuf:"bytes,3,req,name=op" json:"op,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageCSR) Reset()         { *m = MessageCSR{} }
func (m *MessageCSR) String() string { return proto.CompactTextString(m) }
func (*MessageCSR) ProtoMessage()    {}

func (m *MessageCSR) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *MessageCSR) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

func (m *MessageCSR) GetOp() string {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ""
}

// SignedMessage ...
type SignedMessage struct {
	PeerId           *string `protobuf:"bytes,1,req,name=peer_id" json:"peer_id,omitempty"`
	Message          []byte  `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Signature        []byte  `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	PublicKey        *string `protobuf:"bytes,4,req,name=public_key" json:"public_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}

func (m *SignedMessage) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetPublicKey() string {
	if m != nil && m.PublicKey != nil {
		return *m.PublicKey
	}
	return ""
}

func init() {
	proto.RegisterEnum("iam.pb.MessageType", MessageType_name, MessageType_value)
}
