// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package iam_pb is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	MessageCSR
	MessageCOT
	MessageCRT
	MessageCAT
	MessageRT
	SignedMessage
*/
package iam_pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// MessageType ...
type MessageType int32

const (
	MessageType_MessageType_Initialize MessageType = 0
	MessageType_MessageType_MessageCSR MessageType = 1
	MessageType_MessageType_MessageCOT MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MessageType_Initialize",
	1: "MessageType_MessageCSR",
	2: "MessageType_MessageCOT",
}
var MessageType_value = map[string]int32{
	"MessageType_Initialize": 0,
	"MessageType_MessageCSR": 1,
	"MessageType_MessageCOT": 2,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

// Request CSR , owner send to storage
type MessageCSR struct {
	OId              *string `protobuf:"bytes,1,req,name=o_id" json:"o_id,omitempty"`
	Cid              *string `protobuf:"bytes,2,req,name=cid" json:"cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageCSR) Reset()         { *m = MessageCSR{} }
func (m *MessageCSR) String() string { return proto.CompactTextString(m) }
func (*MessageCSR) ProtoMessage()    {}

func (m *MessageCSR) GetOId() string {
	if m != nil && m.OId != nil {
		return *m.OId
	}
	return ""
}

func (m *MessageCSR) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

// CSR Response COT , storage response to owner and signed by storage
type MessageCOT struct {
	SId              *string `protobuf:"bytes,1,req,name=s_id" json:"s_id,omitempty"`
	OId              *string `protobuf:"bytes,2,req,name=o_id" json:"o_id,omitempty"`
	Cid              *string `protobuf:"bytes,3,req,name=cid" json:"cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageCOT) Reset()         { *m = MessageCOT{} }
func (m *MessageCOT) String() string { return proto.CompactTextString(m) }
func (*MessageCOT) ProtoMessage()    {}

func (m *MessageCOT) GetSId() string {
	if m != nil && m.SId != nil {
		return *m.SId
	}
	return ""
}

func (m *MessageCOT) GetOId() string {
	if m != nil && m.OId != nil {
		return *m.OId
	}
	return ""
}

func (m *MessageCOT) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

// CRT Request Token , request send request to owner ask authorization
type MessageCRT struct {
	RId              *string `protobuf:"bytes,1,req,name=r_id" json:"r_id,omitempty"`
	OId              *string `protobuf:"bytes,2,req,name=o_id" json:"o_id,omitempty"`
	Cid              *string `protobuf:"bytes,3,req,name=cid" json:"cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageCRT) Reset()         { *m = MessageCRT{} }
func (m *MessageCRT) String() string { return proto.CompactTextString(m) }
func (*MessageCRT) ProtoMessage()    {}

func (m *MessageCRT) GetRId() string {
	if m != nil && m.RId != nil {
		return *m.RId
	}
	return ""
}

func (m *MessageCRT) GetOId() string {
	if m != nil && m.OId != nil {
		return *m.OId
	}
	return ""
}

func (m *MessageCRT) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

// CRT Response CAT , owner response to requester
type MessageCAT struct {
	OId              *string `protobuf:"bytes,1,req,name=o_id" json:"o_id,omitempty"`
	RId              *string `protobuf:"bytes,2,req,name=r_id" json:"r_id,omitempty"`
	Cid              *string `protobuf:"bytes,3,req,name=cid" json:"cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageCAT) Reset()         { *m = MessageCAT{} }
func (m *MessageCAT) String() string { return proto.CompactTextString(m) }
func (*MessageCAT) ProtoMessage()    {}

func (m *MessageCAT) GetOId() string {
	if m != nil && m.OId != nil {
		return *m.OId
	}
	return ""
}

func (m *MessageCAT) GetRId() string {
	if m != nil && m.RId != nil {
		return *m.RId
	}
	return ""
}

func (m *MessageCAT) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

//
type MessageRT struct {
	RId              *string     `protobuf:"bytes,1,req,name=r_id" json:"r_id,omitempty"`
	Cid              *string     `protobuf:"bytes,2,req,name=cid" json:"cid,omitempty"`
	Cat              *MessageCAT `protobuf:"bytes,3,req,name=cat" json:"cat,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MessageRT) Reset()         { *m = MessageRT{} }
func (m *MessageRT) String() string { return proto.CompactTextString(m) }
func (*MessageRT) ProtoMessage()    {}

func (m *MessageRT) GetRId() string {
	if m != nil && m.RId != nil {
		return *m.RId
	}
	return ""
}

func (m *MessageRT) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

func (m *MessageRT) GetCat() *MessageCAT {
	if m != nil {
		return m.Cat
	}
	return nil
}

// SignedMessage ...
type SignedMessage struct {
	PeerId           *string `protobuf:"bytes,1,req,name=peer_id" json:"peer_id,omitempty"`
	Message          []byte  `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Signature        []byte  `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	PublicKey        *string `protobuf:"bytes,4,req,name=public_key" json:"public_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}

func (m *SignedMessage) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetPublicKey() string {
	if m != nil && m.PublicKey != nil {
		return *m.PublicKey
	}
	return ""
}

func init() {
	proto.RegisterEnum("iam.pb.MessageType", MessageType_name, MessageType_value)
}
