// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package iam_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MessageType ...
type MessageType int32

const (
	MessageType_MessageType_Initialize MessageType = 0
	MessageType_MessageType_MessageCSR MessageType = 1
	MessageType_MessageType_MessageCOT MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MessageType_Initialize",
	1: "MessageType_MessageCSR",
	2: "MessageType_MessageCOT",
}
var MessageType_value = map[string]int32{
	"MessageType_Initialize": 0,
	"MessageType_MessageCSR": 1,
	"MessageType_MessageCOT": 2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{0}
}

// Request CSR , owner send to storage
type MessageCSR struct {
	OId                  []byte   `protobuf:"bytes,1,opt,name=o_id,json=oId,proto3" json:"o_id,omitempty"`
	Cid                  []byte   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCSR) Reset()         { *m = MessageCSR{} }
func (m *MessageCSR) String() string { return proto.CompactTextString(m) }
func (*MessageCSR) ProtoMessage()    {}
func (*MessageCSR) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{0}
}
func (m *MessageCSR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCSR.Unmarshal(m, b)
}
func (m *MessageCSR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCSR.Marshal(b, m, deterministic)
}
func (dst *MessageCSR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCSR.Merge(dst, src)
}
func (m *MessageCSR) XXX_Size() int {
	return xxx_messageInfo_MessageCSR.Size(m)
}
func (m *MessageCSR) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCSR.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCSR proto.InternalMessageInfo

func (m *MessageCSR) GetOId() []byte {
	if m != nil {
		return m.OId
	}
	return nil
}

func (m *MessageCSR) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

// CSR Response COT , storage response to owner and signed by storage
type MessageCOT struct {
	SId                  []byte   `protobuf:"bytes,1,opt,name=s_id,json=sId,proto3" json:"s_id,omitempty"`
	OId                  []byte   `protobuf:"bytes,2,opt,name=o_id,json=oId,proto3" json:"o_id,omitempty"`
	Cid                  []byte   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCOT) Reset()         { *m = MessageCOT{} }
func (m *MessageCOT) String() string { return proto.CompactTextString(m) }
func (*MessageCOT) ProtoMessage()    {}
func (*MessageCOT) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{1}
}
func (m *MessageCOT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCOT.Unmarshal(m, b)
}
func (m *MessageCOT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCOT.Marshal(b, m, deterministic)
}
func (dst *MessageCOT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCOT.Merge(dst, src)
}
func (m *MessageCOT) XXX_Size() int {
	return xxx_messageInfo_MessageCOT.Size(m)
}
func (m *MessageCOT) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCOT.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCOT proto.InternalMessageInfo

func (m *MessageCOT) GetSId() []byte {
	if m != nil {
		return m.SId
	}
	return nil
}

func (m *MessageCOT) GetOId() []byte {
	if m != nil {
		return m.OId
	}
	return nil
}

func (m *MessageCOT) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

// CRT Request Token , request send request to owner ask authorization
type MessageCRT struct {
	RId                  []byte   `protobuf:"bytes,1,opt,name=r_id,json=rId,proto3" json:"r_id,omitempty"`
	OId                  []byte   `protobuf:"bytes,2,opt,name=o_id,json=oId,proto3" json:"o_id,omitempty"`
	Cid                  []byte   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCRT) Reset()         { *m = MessageCRT{} }
func (m *MessageCRT) String() string { return proto.CompactTextString(m) }
func (*MessageCRT) ProtoMessage()    {}
func (*MessageCRT) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{2}
}
func (m *MessageCRT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCRT.Unmarshal(m, b)
}
func (m *MessageCRT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCRT.Marshal(b, m, deterministic)
}
func (dst *MessageCRT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCRT.Merge(dst, src)
}
func (m *MessageCRT) XXX_Size() int {
	return xxx_messageInfo_MessageCRT.Size(m)
}
func (m *MessageCRT) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCRT.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCRT proto.InternalMessageInfo

func (m *MessageCRT) GetRId() []byte {
	if m != nil {
		return m.RId
	}
	return nil
}

func (m *MessageCRT) GetOId() []byte {
	if m != nil {
		return m.OId
	}
	return nil
}

func (m *MessageCRT) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

// CRT Response CAT , owner response to requester
type MessageCAT struct {
	OId                  []byte   `protobuf:"bytes,1,opt,name=o_id,json=oId,proto3" json:"o_id,omitempty"`
	RId                  []byte   `protobuf:"bytes,2,opt,name=r_id,json=rId,proto3" json:"r_id,omitempty"`
	Cid                  []byte   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Cot                  []byte   `protobuf:"bytes,4,opt,name=cot,proto3" json:"cot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCAT) Reset()         { *m = MessageCAT{} }
func (m *MessageCAT) String() string { return proto.CompactTextString(m) }
func (*MessageCAT) ProtoMessage()    {}
func (*MessageCAT) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{3}
}
func (m *MessageCAT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCAT.Unmarshal(m, b)
}
func (m *MessageCAT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCAT.Marshal(b, m, deterministic)
}
func (dst *MessageCAT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCAT.Merge(dst, src)
}
func (m *MessageCAT) XXX_Size() int {
	return xxx_messageInfo_MessageCAT.Size(m)
}
func (m *MessageCAT) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCAT.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCAT proto.InternalMessageInfo

func (m *MessageCAT) GetOId() []byte {
	if m != nil {
		return m.OId
	}
	return nil
}

func (m *MessageCAT) GetRId() []byte {
	if m != nil {
		return m.RId
	}
	return nil
}

func (m *MessageCAT) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *MessageCAT) GetCot() []byte {
	if m != nil {
		return m.Cot
	}
	return nil
}

//
type MessageRT struct {
	RId                  []byte   `protobuf:"bytes,1,opt,name=r_id,json=rId,proto3" json:"r_id,omitempty"`
	Cid                  []byte   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Cat                  []byte   `protobuf:"bytes,3,opt,name=cat,proto3" json:"cat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRT) Reset()         { *m = MessageRT{} }
func (m *MessageRT) String() string { return proto.CompactTextString(m) }
func (*MessageRT) ProtoMessage()    {}
func (*MessageRT) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{4}
}
func (m *MessageRT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRT.Unmarshal(m, b)
}
func (m *MessageRT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRT.Marshal(b, m, deterministic)
}
func (dst *MessageRT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRT.Merge(dst, src)
}
func (m *MessageRT) XXX_Size() int {
	return xxx_messageInfo_MessageRT.Size(m)
}
func (m *MessageRT) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRT.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRT proto.InternalMessageInfo

func (m *MessageRT) GetRId() []byte {
	if m != nil {
		return m.RId
	}
	return nil
}

func (m *MessageRT) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *MessageRT) GetCat() []byte {
	if m != nil {
		return m.Cat
	}
	return nil
}

// SignedMessage ...
type SignedMessage struct {
	PeerId               []byte   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_ac17343918662855, []int{5}
}
func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (dst *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(dst, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageCSR)(nil), "iam.pb.MessageCSR")
	proto.RegisterType((*MessageCOT)(nil), "iam.pb.MessageCOT")
	proto.RegisterType((*MessageCRT)(nil), "iam.pb.MessageCRT")
	proto.RegisterType((*MessageCAT)(nil), "iam.pb.MessageCAT")
	proto.RegisterType((*MessageRT)(nil), "iam.pb.MessageRT")
	proto.RegisterType((*SignedMessage)(nil), "iam.pb.SignedMessage")
	proto.RegisterEnum("iam.pb.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_ac17343918662855) }

var fileDescriptor_messages_ac17343918662855 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0xcd, 0x6a, 0x83, 0x40,
	0x10, 0x07, 0xf0, 0xaa, 0xc1, 0xe0, 0xf4, 0x03, 0xbb, 0x87, 0x56, 0x4a, 0x0b, 0xc5, 0x53, 0xe9,
	0x21, 0x50, 0xfa, 0x04, 0xfd, 0xb8, 0x48, 0x29, 0x01, 0x23, 0xbd, 0xca, 0xea, 0x0e, 0x32, 0x34,
	0x71, 0xc5, 0xdd, 0x1c, 0xec, 0xa5, 0xaf, 0x5e, 0xa2, 0x9b, 0x28, 0xd5, 0x42, 0x8f, 0xf3, 0x1f,
	0xe6, 0xe7, 0xe0, 0x0e, 0x9c, 0x6d, 0x50, 0x29, 0x5e, 0xa0, 0x5a, 0x54, 0xb5, 0xd4, 0x92, 0xb9,
	0xc4, 0x37, 0x8b, 0x2a, 0x0b, 0x1f, 0x00, 0xde, 0xbb, 0xce, 0xcb, 0x2a, 0x66, 0xe7, 0x30, 0x93,
	0x29, 0x89, 0xc0, 0xba, 0xb5, 0xee, 0x4e, 0x62, 0x47, 0x46, 0x82, 0xf9, 0xe0, 0xe4, 0x24, 0x02,
	0xbb, 0x4b, 0x72, 0x12, 0xe1, 0x6b, 0x3f, 0xb2, 0x4c, 0x76, 0x23, 0x6a, 0x30, 0xa2, 0x22, 0x71,
	0x50, 0xec, 0x91, 0xe2, 0x4c, 0x2a, 0x71, 0xab, 0xd4, 0x03, 0xa5, 0xfe, 0xaf, 0xf2, 0xd1, 0x2b,
	0x4f, 0xc9, 0xd4, 0xfa, 0x7b, 0xd8, 0xee, 0xe1, 0x91, 0xd2, 0x26, 0x52, 0x07, 0x33, 0x93, 0x48,
	0x1d, 0x3e, 0x83, 0x67, 0xdc, 0xe9, 0xe5, 0x46, 0x7f, 0xa5, 0x4d, 0xb8, 0x3e, 0xa8, 0x5c, 0x87,
	0xdf, 0x70, 0xba, 0xa2, 0xa2, 0x44, 0x61, 0x24, 0x76, 0x09, 0xf3, 0x0a, 0x71, 0x40, 0xb9, 0xbb,
	0x32, 0x12, 0x2c, 0x80, 0xb9, 0x79, 0x1e, 0x23, 0xee, 0x4b, 0x76, 0x0d, 0x9e, 0xa2, 0xa2, 0xe4,
	0x7a, 0x5b, 0xa3, 0xb1, 0xfb, 0x80, 0xdd, 0x00, 0x54, 0xdb, 0x6c, 0x4d, 0x79, 0xfa, 0x89, 0x8d,
	0x59, 0xdf, 0xeb, 0x92, 0x37, 0x6c, 0xee, 0x39, 0x1c, 0x9b, 0x4f, 0x27, 0x4d, 0x85, 0xec, 0x0a,
	0x2e, 0x06, 0x65, 0x1a, 0x95, 0xa4, 0x89, 0xaf, 0xe9, 0x0b, 0xfd, 0xa3, 0xdf, 0xbd, 0xfe, 0x24,
	0x7c, 0xeb, 0xaf, 0xde, 0x32, 0xf1, 0xed, 0xcc, 0x6d, 0xaf, 0xe9, 0xf1, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x86, 0x18, 0xe8, 0x2c, 0x5f, 0x02, 0x00, 0x00,
}
